git:
  depth: 3
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - '6'
env:
  - EXTENSION_ID=cjbacdldhllelehomkmlniifaojgaeph
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
